repositoryUrl: https://github.com/Mark-Dynamsoft/DBRDoc/blob/master
repository: Mark-Dynamsoft/DBRDoc
docFullPath: https://mark-dynamsoft.github.io/DBRDoc
firstLevelUrl: /DBRDoc
docHomePage: /DBRDoc/introduction/

useVersionTree: true

introduction: /DBRDoc/introduction/
programming: /DBRDoc/programming/
parameters: /DBRDoc/parameters/
license_activation: /DBRDoc/license-activation/
enhancements: /DBRDoc/enhancements/
release_notes: /DBRDoc/release-notes/

comparison_tools: /DBRDoc/introduction/comparison-tools/

c_cplusplus: /DBRDoc/programming/c-cplusplus/
structs: /DBRDoc/programming/c-cplusplus/struct/

c: /DBRDoc/programming/c/
c_api: /DBRDoc/programming/c/api-reference/
c_methods: /DBRDoc/programming/c/api-reference/methods/
c_release_notes: /DBRDoc/programming/c/release-notes/

cpp: /DBRDoc/programming/cplusplus/
cpp_api: /DBRDoc/programming/cplusplus/api-reference/
cpp_methods: /DBRDoc/programming/cplusplus/api-reference/cbarcodereader-methods/
cpp_release_notes: /DBRDoc/programming/cplusplus/release-notes/

js: /DBRDoc/programming/javascript/
js_api: /DBRDoc/programming/javascript/api-reference/
js_release_notes: /DBRDoc/programming/javascript/release-notes/

dotnet: /DBRDoc/programming/dotnet/
dotnet_api: /DBRDoc/programming/dotnet/api-reference/
dotnet_methods: /DBRDoc/programming/dotnet/api-reference/BarcodeReader/
dotnet_class: /DBRDoc/programming/dotnet/api-reference/class/
dotnet_release_notes: /DBRDoc/programming/dotnet/release-notes/

oc: /DBRDoc/programming/objectivec-swift/
oc_api: /DBRDoc/programming/objectivec-swift/api-reference/
oc_release_notes: /DBRDoc/programming/objectivec-swift/release-notes/
oc_methods: /DBRDoc/programming/objectivec-swift/api-reference/methods/
oc_class: /DBRDoc/programming/objectivec-swift/api-reference/class/
oc_methods: /DBRDoc/programming/objectivec-swift/api-reference/methods/

java: /DBRDoc/programming/java/
java_api: /DBRDoc/programming/java/api-reference/
java_methods: /DBRDoc/programming/java/api-reference/BarcodeReader/
java_class: /DBRDoc/programming/java/api-reference/class/
java_release_notes: /DBRDoc/programming/java/release-notes/

android: /DBRDoc/programming/android/
android_api: /DBRDoc/programming/android/api-reference/
android_release_notes: /DBRDoc/programming/android/release-notes/
android_class: /DBRDoc/programming/android/api-reference/class/
android_methods: /DBRDoc/programming/android/api-reference/BarcodeReader/
  
python: /DBRDoc/programming/python/
python_api: /DBRDoc/programming/python/api-reference/
python_methods: /DBRDoc/programming/python/api-reference/BarcodeReader/
python_class: /DBRDoc/programming/python/api-reference/class/
python_release_notes: /DBRDoc/programming/python/release-notes/

parameters_reference: /DBRDoc/parameters/reference/
image_parameters: /DBRDoc/parameters/reference/image-parameter/
scenario_settings: /DBRDoc/parameters/scenario-settings/
enumerations: /DBRDoc/parameters/enum/

faqs: /DBRDoc/introduction/faqs.html
how_to: /DBRDoc/introduction/how-to-guide/

assets: /DBRDoc/assets/
edit_icon: /DBRDoc/assets/img-icon/edit-icon.png
smile_icon: /DBRDoc/assets/img-icon/icon-smile.png
sad_icon: /DBRDoc/assets/img-icon/icon-sad.png
dbr_icon: /DBRDoc/assets/img-icon/icon-dbr.svg
dwt_icon: /DBRDoc/assets/img-icon/icon-dwt.svg
dnt_icon: /DBRDoc/assets/img-icon/icon-dnt.svg

camera: /camera-enhancer/docs/introduction/

baseurl: ""
plugins:
  - jemoji
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      category: "original-repo"
  - scope:
      path: "programming/javascript"
    values:
      category: "js-repo"
  - scope:
      path: "programming/android"
    values:
      category: "mobile-repo"
  - scope:
      path: "programming/objectivec-swift"
    values:
      category: "mobile-repo"
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true
  - scope:
      path: "Hide_Tree_Page.html"
    values:
      sitemap: false

url: "https://www.dynamsoft.com" # sitemap root
